# frozen_string_literal: true

module Constants
  MAX_NAME_LENGTH = 50
  MAX_TITLE_LENGTH = 200
  MAX_CONTENT_LENGTH = 3000
  MAX_SITE_NAME_LENGTH = 20
  MIN_PASSWORD_LENGTH = 6
  MAX_FROM_PATH_LENGTH = 200
  MAX_TO_PATH_LENGTH = 200
end
